version: 0.2
env:
  parameter-store:
    DOCKERHUB_USERNAME: /Codebuild/Dockerhub/Username
    DOCKERHUB_PASSWORD: /Codebuild/Dockerhub/Password

phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_PASSWORD} | docker login --username ${DOCKERHUB_USERNAME}  --password-stdin
      - REPO_NAME=${DOCKERHUB_USERNAME}/gdal-subsetter
      - VERSION=v$(cat version.txt)
      - TAG=${REPO_NAME}:${VERSION}
  build:
    commands:
      - docker build -t ${TAG} .
  post_build:
    commands:
      - docker push ${TAG}
