version: 0.2
env:
  parameter-store:
    DOCKERHUB_USERNAME: /Codebuild/Dockerhub/Username
    DOCKERHUB_PASSWORD: /Codebuild/Dockerhub/Password

phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_PASSWORD} | docker login --username ${DOCKERHUB_USERNAME}  --password-stdin
      - mkdir deps && aws s3 sync s3://asf-harmony-service-lib-py deps
      - REPO_NAME=${DOCKERHUB_USERNAME}/gdal-subsetter
      - GIT_HASH_NAME=${REPO_NAME}:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - HARMONY_TAG=${REPO_NAME}:${MATURITY}
  build:
    commands:
      - docker build -t ${GIT_HASH_NAME} .
      - docker tag ${GIT_HASH_NAME} ${REPO_NAME}:latest
      - docker tag ${GIT_HASH_NAME} ${HARMONY_TAG}
  post_build:
    commands:
      - docker push ${HARMONY_TAG}
      - docker push ${GIT_HASH_NAME}
