version: 0.2
env:
    parameter-store:
        DOCKERHUB-USERNAME: dockerhub-username
        DOCKERHUB-PASSWORD: dockerhub-password

phases:
  pre_build:
    commands:
      - echo $DOCKERHUB-USERNAME
      - echo ${DOCKERHUB-PASSWORD} | docker login --username ${DOCKERHUB-USERNAME}  --password-stdin
      - mkdir deps && aws s3 sync s3://asf-harmony-service-lib-py deps
  build:
    commands:
      - docker build -t ${DOCKERHUB-USERNAME}/gdal-subsetter:latest .
  post_build:
    commands:
      - docker push ${DOCKERHUB-USERNAME}/gdal-subsetter:tagname
