version: 0.2
env:
    parameter-store:
        DOCKERHUB-USERNAME: dockerhub-username
        DOCKERHUB-PASSWORD: dockerhub-password

phases:
  pre_build:
    commands:
      - docker login --user ${DOCKERHUB-USERNAME}  --password ${DOCKERHUB-PASSWORD}
      - mkdir deps && aws s3 sync s3://asf-harmony-service-lib-py deps
  build:
    commands:
      - docker build -t ${DOCKERHUB-USERNAME}/gdal-subsetter:latest .
  post_build:
    commands:
      - docker push ${DOCKERHUB-USERNAME}/gdal-subsetter:tagname
