version: 0.2
env:
  parameter-store:
    DOCKERHUB_USERNAME: /Codebuild/Dockerhub/Username
    DOCKERHUB_PASSWORD: /Codebuild/Dockerhub/Password

phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_PASSWORD} | docker login --username ${DOCKERHUB_USERNAME}  --password-stdin
      - mkdir deps && aws s3 sync s3://asf-harmony-service-lib-py deps
  build:
    commands:
      - docker build -t ${DOCKERHUB_USERNAME}/gdal-subsetter:${CODEBUILD_RESOLVED_SOURCE_VERSION} .
      - docker tag ${DOCKERHUB_USERNAME}/gdal-subsetter:${CODEBUILD_RESOLVED_SOURCE_VERSION} ${DOCKERHUB_USERNAME}/gdal-subsetter:latest
  post_build:
    commands:
      - docker push ${DOCKERHUB_USERNAME}/gdal-subsetter:${CODEBUILD_RESOLVED_SOURCE_VERSION}
