version: 0.2
env:
  parameter-store:
    EDL_USERNAME: /Codebuild/EDL/Username
    EDL_PASSWORD: /Codebuild/EDL/Password

phases:
  pre_build:
    commands:
      - echo 'installing deps'
  build:
    commands:
      - echo 'running unittests'
  post_build:
    commands:
      - echo 'update badges'
