version: 0.2
env:
  parameter-store:
    EDL_USERNAME: /Codebuild/EDL/Username
    EDL_PASSWORD: /Codebuild/EDL/Password

phases:
  pre_build:
    commands:
      - echo 'installing deps'
      - pip3 install -r requirements.txt
      - pip3 install deps/harmony-service-lib-py
  build:
    commands:
      - echo 'running unittests'
      - cd unittest
      - coverage run -m pytest -v test_all_message.py
  post_build:
    commands:
      - echo 'update badges'
